import type { DomainRecords, Task } from './model';

const now = '2026-07-01T09:00:00.000Z';

const task = (overrides: Partial<Task> & Pick<Task, 'id' | 'title' | 'summary'>): Task => ({
  projectId: 'project-orchestrator',
  repoId: 'repo-orchestrator',
  branchId: 'branch-main',
  worktreeId: 'worktree-main',
  executionState: 'draft',
  attentionState: 'consider_later',
  conversationIds: [],
  priority: 'normal',
  createdAt: now,
  updatedAt: now,
  ...overrides,
});

export const seedDomainRecords: DomainRecords = {
  projects: [
    {
      id: 'project-orchestrator',
      name: 'Codex Orchestrator',
      description: 'Local-first control plane for Codex-driven implementation work.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'project-runtime',
      name: 'Runtime Architecture',
      createdAt: now,
      updatedAt: now,
    },
  ],
  repos: [
    {
      id: 'repo-orchestrator',
      projectId: 'project-orchestrator',
      name: 'CodexOrchestrator',
      rootPath: 'C:\\Users\\user\\Documents\\Code Projects\\Codex Orchestrator',
      defaultBranch: 'main',
      remoteUrl: 'https://github.com/andreas-kielsgaard/CodexOrchestrator',
      createdAt: now,
      updatedAt: now,
    },
  ],
  branches: [
    {
      id: 'branch-main',
      repoId: 'repo-orchestrator',
      name: 'main',
      intent: 'Stable reviewed project state.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'branch-domain',
      repoId: 'repo-orchestrator',
      name: 'worker/002-domain-model',
      baseBranch: 'main',
      intent: 'Add domain model and dashboard projection foundation.',
      createdAt: now,
      updatedAt: now,
    },
  ],
  worktrees: [
    {
      id: 'worktree-main',
      repoId: 'repo-orchestrator',
      branchId: 'branch-main',
      path: 'C:\\Users\\user\\Documents\\Code Projects\\Codex Orchestrator',
      isMain: true,
      isDirty: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'worktree-domain',
      repoId: 'repo-orchestrator',
      branchId: 'branch-domain',
      path: 'C:\\Users\\user\\.codex\\worktrees\\eaeb\\Codex Orchestrator',
      isMain: false,
      isDirty: true,
      createdAt: now,
      updatedAt: now,
    },
  ],
  conversations: [
    {
      id: 'conversation-worker-002',
      taskId: 'task-domain-model',
      taskRunId: 'run-domain-model',
      provider: 'codex',
      externalThreadId: '019f1f99-5c3f-7961-874e-6af58a7c3ec5',
      title: 'Worker 002 domain model implementation',
      createdAt: now,
      updatedAt: now,
    },
  ],
  tasks: [
    task({
      id: 'task-bootstrap-review',
      title: 'Resolve bootstrap blockers',
      summary: 'Install Rust locally before desktop shell verification can run.',
      executionState: 'blocked',
      attentionState: 'needs_action_now',
      priority: 'high',
      updatedAt: '2026-07-01T13:10:00.000Z',
    }),
    task({
      id: 'task-domain-model',
      title: 'Review domain projection slice',
      summary: 'Domain types and dashboard buckets are complete but still need human review.',
      branchId: 'branch-domain',
      worktreeId: 'worktree-domain',
      conversationIds: ['conversation-worker-002'],
      executionState: 'completed',
      attentionState: 'needs_review',
      updatedAt: '2026-07-01T13:00:00.000Z',
    }),
    task({
      id: 'task-dashboard-shell',
      title: 'Dashboard shell',
      summary: 'Agent is actively shaping the attention-first task surface.',
      executionState: 'running',
      attentionState: 'waiting_on_agent',
      updatedAt: '2026-07-01T12:55:00.000Z',
    }),
    task({
      id: 'task-domain-schema',
      title: 'SQLite schema slice',
      summary: 'Waiting for domain model review before adding persistence migrations.',
      executionState: 'draft',
      attentionState: 'waiting_on_external',
      updatedAt: '2026-07-01T12:40:00.000Z',
    }),
    task({
      id: 'task-chatgpt-import',
      title: 'ChatGPT export import',
      summary: 'Archive, search, and linking workflow belongs after core task runs.',
      projectId: 'project-runtime',
      repoId: undefined,
      branchId: undefined,
      worktreeId: undefined,
      executionState: 'draft',
      attentionState: 'consider_later',
      updatedAt: '2026-07-01T12:20:00.000Z',
    }),
  ],
  taskRuns: [
    {
      id: 'run-domain-model',
      taskId: 'task-domain-model',
      conversationId: 'conversation-worker-002',
      worktreeId: 'worktree-domain',
      executionState: 'completed',
      startedAt: '2026-07-01T12:15:00.000Z',
      completedAt: '2026-07-01T13:00:00.000Z',
      createdAt: '2026-07-01T12:15:00.000Z',
      updatedAt: '2026-07-01T13:00:00.000Z',
    },
  ],
  artifacts: [
    {
      id: 'artifact-domain-summary',
      taskId: 'task-domain-model',
      taskRunId: 'run-domain-model',
      conversationId: 'conversation-worker-002',
      kind: 'summary',
      title: 'Domain model implementation summary',
      content: 'Types, seed records, and dashboard projection implemented without persistence.',
      createdAt: '2026-07-01T13:00:00.000Z',
    },
  ],
  validationRuns: [
    {
      id: 'validation-domain-tests',
      taskId: 'task-domain-model',
      taskRunId: 'run-domain-model',
      command: 'npm run test',
      status: 'passed',
      startedAt: '2026-07-01T12:58:00.000Z',
      completedAt: '2026-07-01T12:59:00.000Z',
      exitCode: 0,
      createdAt: '2026-07-01T12:58:00.000Z',
      updatedAt: '2026-07-01T12:59:00.000Z',
    },
  ],
  events: [
    {
      id: 'event-domain-attention',
      kind: 'attention_changed',
      occurredAt: '2026-07-01T13:00:00.000Z',
      projectId: 'project-orchestrator',
      taskId: 'task-domain-model',
      taskRunId: 'run-domain-model',
      conversationId: 'conversation-worker-002',
      payload: {
        from: 'waiting_on_agent',
        to: 'needs_review',
      },
    },
  ],
};
