/** Recorded-only catalog for Harness Management development evidence. */
export const productDefaultAgentNames = [
  'Ada Lovelace',
  'Antoni Gaudi',
  'Grace Hopper',
  'Alan Turing',
  'Hedy Lamarr',
  'Claude Shannon',
  'Margaret Hamilton',
  'Katherine Johnson',
  'Radia Perlman',
  'Barbara Liskov',
  'Annie Easley',
  'Mary Jackson',
  'Dorothy Vaughan',
  'Jean Bartik',
  'Frances Allen',
  'Karen Sparck Jones',
  'Evelyn Boyd Granville',
  'Joan Clarke',
  'John von Neumann',
  'Donald Knuth',
  'Edsger Dijkstra',
  'Niklaus Wirth',
  'John Backus',
  'Ken Thompson',
  'Dennis Ritchie',
  'Brian Kernighan',
  'Alan Kay',
  'Douglas Engelbart',
  'Vint Cerf',
  'Bob Kahn',
  'Tim Berners-Lee',
  'James Gosling',
  'Guido van Rossum',
  'Yukihiro Matsumoto',
  'Brendan Eich',
  'Linus Torvalds',
  'Ken Kutaragi',
  'Shigeru Miyamoto',
  'Gunpei Yokoi',
  'Roberta Williams',
  'Carol Shaw',
  'Dona Bailey',
  'Ralph Baer',
  'Nolan Bushnell',
  'Sid Meier',
  'Will Wright',
  'Satoshi Tajiri',
  'John Carmack',
  'John Romero',
  'Jordan Mechner',
  'Zaha Hadid',
  'Maya Lin',
  'I M Pei',
  'Frank Lloyd Wright',
  'Eero Saarinen',
  'Lina Bo Bardi',
  'Le Corbusier',
  'Buckminster Fuller',
  'Jane Jacobs',
  'Christopher Wren',
  'Vitruvius',
  'Isambard Brunel',
  'Emily Roebling',
  'Fazlur Rahman Khan',
  'Gustave Eiffel',
  'Joseph Strauss',
  'Santiago Calatrava',
  'Norman Foster',
  'Renzo Piano',
  'Moshe Safdie',
  'Usain Bolt',
  'Wilma Rudolph',
  'Eliud Kipchoge',
  'Kathrine Switzer',
  'Roger Bannister',
  'Florence Griffith Joyner',
  'Abebe Bikila',
  'Joan Benoit',
  'Steve Prefontaine',
  'Allyson Felix',
  'Jackie Joyner-Kersee',
  'Jesse Owens',
  'Emil Zatopek',
  'Paavo Nurmi',
  'Fanny Blankers-Koen',
  'Cathy Freeman',
  'Michael Johnson',
  'Haile Gebrselassie',
  'Mo Farah',
  'Sifan Hassan',
  'Archimedes',
  'Hypatia',
  'Leonardo da Vinci',
  'Johannes Gutenberg',
  'Johannes Kepler',
  'Marie Curie',
  'Niels Bohr',
  'Emmy Noether',
  'Srinivasa Ramanujan',
  'George Boole',
] as const;

export const harnessAgentNamePools = {
  epic_plan_builder: [
    'Antoni Gaudi',
    'Zaha Hadid',
    'Maya Lin',
    'I M Pei',
    'Frank Lloyd Wright',
    'Eero Saarinen',
    'Lina Bo Bardi',
    'Buckminster Fuller',
    'Jane Jacobs',
    'Christopher Wren',
  ],
  epic_bootstrap_generator: [
    'Ada Lovelace',
    'Grace Hopper',
    'Alan Turing',
    'Hedy Lamarr',
    'Claude Shannon',
    'Margaret Hamilton',
    'Radia Perlman',
    'Barbara Liskov',
    'Annie Easley',
    'Jean Bartik',
  ],
  epic_runner: [
    'Usain Bolt',
    'Wilma Rudolph',
    'Eliud Kipchoge',
    'Kathrine Switzer',
    'Roger Bannister',
    'Florence Griffith Joyner',
    'Abebe Bikila',
    'Joan Benoit',
    'Steve Prefontaine',
    'Allyson Felix',
  ],
} as const;

export const harnessVisualIdentities = {
  epic_plan_builder: { token: 'drafting_compass', accent: '#39745a' },
  epic_bootstrap_generator: { token: 'bootstrap_package', accent: '#9a6730' },
  epic_runner: { token: 'runner_route', accent: '#466d98' },
} as const;

export function validateAgentNamePool(pool: readonly string[]): readonly string[] {
  if (pool.length === 0) throw new Error('Agent name pool must not be empty.');
  const names = pool.map((name) => name.trim());
  if (names.some((name) => !name)) throw new Error('Agent names must not be blank.');
  if (new Set(names.map((name) => name.toLocaleLowerCase('en-US'))).size !== names.length)
    throw new Error('Agent names must be unique.');
  return names;
}
