//! Application-owned acceptance integration.  It has no transport surface.

use rusqlite::{params, Connection, OptionalExtension, TransactionBehavior};
use sha2::{Digest, Sha256};
use std::{fs::{self, OpenOptions}, path::{Path, PathBuf}, process::{Command, Stdio}, io::Write};

const SCHEMA: &str = r#"
CREATE TABLE IF NOT EXISTS accepted_work_unit_integrations (
 integration_id TEXT PRIMARY KEY, work_unit_id TEXT NOT NULL UNIQUE REFERENCES work_units(work_unit_id), candidate_id TEXT NOT NULL UNIQUE REFERENCES accepted_handler_candidates(candidate_id), authority_id TEXT NOT NULL REFERENCES initiated_sprint_git_authorities(authority_id), target_ref_name TEXT NOT NULL, pre_object_id TEXT NOT NULL, pre_version INTEGER NOT NULL, candidate_commit_id TEXT NOT NULL, candidate_tree_id TEXT NOT NULL, baseline_object_id TEXT NOT NULL, intent_fingerprint TEXT NOT NULL UNIQUE, intent_recorded_at TEXT NOT NULL, integration_commit_id TEXT, integration_tree_id TEXT, object_created_at TEXT, ref_advanced_at TEXT, runtime_advanced_at TEXT, db_advanced_at TEXT, settled_at TEXT, notification_intent_recorded_at TEXT, notification_delivered_at TEXT, attention_code TEXT, attention_recorded_at TEXT, CHECK ((attention_code IS NULL) = (attention_recorded_at IS NULL))
);
CREATE TABLE IF NOT EXISTS work_unit_settlements (settlement_id TEXT PRIMARY KEY, work_unit_id TEXT NOT NULL UNIQUE REFERENCES work_units(work_unit_id), integration_id TEXT NOT NULL UNIQUE REFERENCES accepted_work_unit_integrations(integration_id), settled_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS work_unit_prerequisite_contributions (contribution_id TEXT PRIMARY KEY, prerequisite_work_unit_id TEXT NOT NULL REFERENCES work_units(work_unit_id), dependent_work_unit_id TEXT NOT NULL REFERENCES work_units(work_unit_id), integration_id TEXT NOT NULL REFERENCES accepted_work_unit_integrations(integration_id), relationship_id TEXT NOT NULL UNIQUE REFERENCES work_unit_relationships(relationship_id), recorded_at TEXT NOT NULL, UNIQUE(prerequisite_work_unit_id,dependent_work_unit_id,integration_id));
"#;
#[derive(Clone)] struct Row{candidate:String,unit:String,authority:String,repo:PathBuf,common:PathBuf,worktree:PathBuf,baseline:String,commit:String,tree:String,private_ref:String,evidence:String,reference:String,current:String,version:i64}

pub(crate) fn reconcile_accepted_integrations(c:&mut Connection)->Result<(),String>{
 c.execute_batch(SCHEMA).map_err(|e|e.to_string())?;
 let rows=c.prepare("SELECT c.candidate_id,c.work_unit_id,c.authority_id,a.repository_root,a.repository_common_dir,a.worktree_root,a.baseline_object_id,c.candidate_commit_id,c.candidate_tree_id,c.private_ref_name,c.evidence_fingerprint,t.target_ref_name,t.current_object_id,t.version FROM accepted_handler_candidates c JOIN initiated_sprint_git_authorities a ON a.authority_id=c.authority_id JOIN sprint_target_currents t ON t.authority_id=c.authority_id WHERE c.pinned_at IS NOT NULL AND c.attention_reason IS NULL AND t.attention_reason IS NULL ORDER BY c.work_unit_id").map_err(|e|e.to_string())?.query_map([],|r|Ok(Row{candidate:r.get(0)?,unit:r.get(1)?,authority:r.get(2)?,repo:PathBuf::from(r.get::<_,String>(3)?),common:PathBuf::from(r.get::<_,String>(4)?),worktree:PathBuf::from(r.get::<_,String>(5)?),baseline:r.get(6)?,commit:r.get(7)?,tree:r.get(8)?,private_ref:r.get(9)?,evidence:r.get(10)?,reference:r.get(11)?,current:r.get(12)?,version:r.get(13)?})).map_err(|e|e.to_string())?.collect::<Result<Vec<_>,_>>().map_err(|e|e.to_string())?;
 for row in rows { if let Err(code)=one(c,&row){ attention(c,&row.candidate,&code)?; } } Ok(())
}
fn one(c:&mut Connection,r:&Row)->Result<(),String>{
 let iid=id("accepted-work-unit-integration",&r.candidate); let old:Option<(String,String,i64,String,Option<String>,Option<String>)>=c.query_row("SELECT target_ref_name,pre_object_id,pre_version,candidate_commit_id,integration_commit_id,settled_at FROM accepted_work_unit_integrations WHERE candidate_id=?1",[&r.candidate],|x|Ok((x.get(0)?,x.get(1)?,x.get(2)?,x.get(3)?,x.get(4)?,x.get(5)?))).optional().map_err(|e|e.to_string())?;
 if let Some((reference,pre,ver,candidate,commit,settled))=old {if reference!=r.reference||candidate!=r.commit{return Err("durable_integration_mismatch".into())}if settled.is_some(){return Ok(())}return resume(c,r,&iid,&pre,ver,commit.as_deref())}
 preflight(r,&r.current)?;let now=chrono::Utc::now().to_rfc3339();let intent=hash(&[&iid,&r.unit,&r.candidate,&r.authority,&r.reference,&r.current,&r.version.to_string(),&r.baseline,&r.commit,&r.tree,&r.evidence]);let tx=c.transaction_with_behavior(TransactionBehavior::Immediate).map_err(|e|e.to_string())?;tx.execute("INSERT INTO accepted_work_unit_integrations(integration_id,work_unit_id,candidate_id,authority_id,target_ref_name,pre_object_id,pre_version,candidate_commit_id,candidate_tree_id,baseline_object_id,intent_fingerprint,intent_recorded_at)VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12)",params![iid,r.unit,r.candidate,r.authority,r.reference,r.current,r.version,r.commit,r.tree,r.baseline,intent,now]).map_err(|e|e.to_string())?;tx.commit().map_err(|e|e.to_string())?;resume(c,r,&iid,&r.current,r.version,None)
}
fn resume(c:&mut Connection,r:&Row,iid:&str,pre:&str,version:i64,stored:Option<&str>)->Result<(),String>{let _lock=Lock::take(&r.common,&r.reference)?;let commit=match stored{Some(v)=>{verify(r,iid,pre,v)?;v.to_owned()},None=>{preflight(r,pre)?;let tree=merged_tree(r,pre)?;let value=create(c,r,iid,pre,&tree)?;verify(r,iid,pre,&value)?;c.execute("UPDATE accepted_work_unit_integrations SET integration_commit_id=?2,integration_tree_id=?3,object_created_at=COALESCE(object_created_at,?4) WHERE integration_id=?1",params![iid,value,tree,chrono::Utc::now().to_rfc3339()]).map_err(|e|e.to_string())?;value}};
 let actual=git(&r.worktree,&["show-ref","--verify","--hash",&r.reference])?;if actual==pre{let _=git(&r.worktree,&["update-ref",&r.reference,&commit,pre]).map_err(|_|"target_ref_cas_lost".to_string())?;}else if actual!=commit{return Err("target_ref_advanced_or_foreign".into())};c.execute("UPDATE accepted_work_unit_integrations SET ref_advanced_at=COALESCE(ref_advanced_at,?2) WHERE integration_id=?1",params![iid,chrono::Utc::now().to_rfc3339()]).map_err(|e|e.to_string())?;
 git(&r.worktree,&["read-tree","--reset","-u",&commit])?;if git(&r.worktree,&["rev-parse","HEAD^{commit}"])?!=commit||git(&r.worktree,&["status","--porcelain"])?!=""{return Err("target_runtime_convergence_failed".into())};c.execute("UPDATE accepted_work_unit_integrations SET runtime_advanced_at=COALESCE(runtime_advanced_at,?2) WHERE integration_id=?1",params![iid,chrono::Utc::now().to_rfc3339()]).map_err(|e|e.to_string())?;
 let tx=c.transaction_with_behavior(TransactionBehavior::Immediate).map_err(|e|e.to_string())?;let changed=tx.execute("UPDATE sprint_target_currents SET current_object_id=?2,version=version+1,updated_at=?3 WHERE authority_id=?1 AND current_object_id=?4 AND version=?5",params![r.authority,commit,chrono::Utc::now().to_rfc3339(),pre,version]).map_err(|e|e.to_string())?;if changed==0{let exact:bool=tx.query_row("SELECT EXISTS(SELECT 1 FROM sprint_target_currents WHERE authority_id=?1 AND current_object_id=?2 AND version=?3)",params![r.authority,commit,version+1],|x|x.get(0)).map_err(|e|e.to_string())?;if !exact{return Err("target_current_cas_lost".into())}}tx.execute("UPDATE accepted_work_unit_integrations SET db_advanced_at=COALESCE(db_advanced_at,?2) WHERE integration_id=?1",params![iid,chrono::Utc::now().to_rfc3339()]).map_err(|e|e.to_string())?;tx.commit().map_err(|e|e.to_string())?;settle(c,r,iid)
}
fn preflight(r:&Row,pre:&str)->Result<(),String>{if !safe_ref(&r.reference)||!oid(pre)||!oid(&r.baseline)||!oid(&r.commit){return Err("unsafe_durable_identity".into())}let common=PathBuf::from(git(&r.worktree,&["rev-parse","--git-common-dir"])?);let common=if common.is_absolute(){common}else{r.worktree.join(common)};if canon(&r.repo)?!=canon(&r.worktree)?||canon(&common)?!=canon(&r.common)?{return Err("target_common_dir_drift".into())}if git(&r.worktree,&["status","--porcelain"])?!=""{return Err("target_worktree_dirty".into())}if git(&r.worktree,&["symbolic-ref","--quiet","HEAD"])?!=r.reference||git(&r.worktree,&["rev-parse","HEAD^{commit}"])?!=pre||git(&r.worktree,&["show-ref","--verify","--hash",&r.reference])?!=pre{return Err("target_ref_or_head_drift".into())}if git(&r.repo,&["show-ref","--verify","--hash",&r.private_ref])?!=r.commit||git(&r.repo,&["rev-parse",&format!("{}^{{tree}}",r.commit)])?!=r.tree{return Err("candidate_private_ref_drift".into())}if git(&r.repo,&["merge-base","--is-ancestor",&r.baseline,&r.commit]).is_err(){return Err("candidate_baseline_drift".into())}Ok(())}
fn merged_tree(r:&Row,pre:&str)->Result<String,String>{let d=std::env::temp_dir().join(format!("codex-integration-{}",uuid::Uuid::new_v4()));fs::create_dir_all(&d).map_err(|_|"temporary_index_unavailable".to_string())?;let i=d.join("index");let result=git_index(&r.repo,&["read-tree","-m",&r.baseline,pre,&r.commit],&i).and_then(|_|git_index(&r.repo,&["write-tree"],&i));let _=fs::remove_dir_all(d);result.map_err(|_|"integration_conflict".into())}
fn create(c:&Connection,r:&Row,iid:&str,pre:&str,tree:&str)->Result<String,String>{let date:String=c.query_row("SELECT intent_recorded_at FROM accepted_work_unit_integrations WHERE integration_id=?1",[iid],|x|x.get(0)).map_err(|e|e.to_string())?;let author=git(&r.repo,&["show","-s","--format=%an%x00%ae%x00%aI",&r.commit])?;let mut a=author.split('\0');let(n,e,d)=(a.next().ok_or("candidate_author_invalid")?,a.next().ok_or("candidate_author_invalid")?,a.next().ok_or("candidate_author_invalid")?);let message=format!("Codex Orchestrator accepted Work Unit integration\n\nIntegration: {iid}\nCandidate: {}\nWork-Unit: {}\nAuthority: {}\n",r.candidate,r.unit,r.authority);let mut p=Command::new("git").args(["commit-tree",tree,"-p",pre]).current_dir(&r.repo).env("GIT_AUTHOR_NAME",n).env("GIT_AUTHOR_EMAIL",e).env("GIT_AUTHOR_DATE",d).env("GIT_COMMITTER_NAME","Codex Orchestrator").env("GIT_COMMITTER_EMAIL","orchestrator@local.invalid").env("GIT_COMMITTER_DATE",date).stdin(Stdio::piped()).stdout(Stdio::piped()).spawn().map_err(|_|"git_unavailable".to_string())?;p.stdin.as_mut().ok_or("git_unavailable")?.write_all(message.as_bytes()).map_err(|_|"git_command_failed".to_string())?;let o=p.wait_with_output().map_err(|_|"git_command_failed".to_string())?;if o.status.success(){Ok(String::from_utf8_lossy(&o.stdout).trim().to_owned())}else{Err("git_command_failed".into())}}
fn verify(r:&Row,iid:&str,pre:&str,commit:&str)->Result<(),String>{if git(&r.repo,&["rev-list","--parents","-n","1",commit])?!=format!("{commit} {pre}"){return Err("integration_parent_mismatch".into())}if git(&r.repo,&["rev-parse",&format!("{commit}^{{tree}}")])?!=merged_tree(r,pre)?{return Err("integration_tree_mismatch".into())}let message=git(&r.repo,&["show","-s","--format=%B",commit])?;if !message.contains(&format!("Integration: {iid}"))||!message.contains(&format!("Candidate: {}",r.candidate))||!message.contains(&format!("Work-Unit: {}",r.unit))||!message.contains(&format!("Authority: {}",r.authority)){return Err("integration_metadata_mismatch".into())}Ok(())}
fn settle(c:&mut Connection,r:&Row,iid:&str)->Result<(),String>{let now=chrono::Utc::now().to_rfc3339();let tx=c.transaction_with_behavior(TransactionBehavior::Immediate).map_err(|e|e.to_string())?;tx.execute("INSERT OR IGNORE INTO work_unit_settlements(settlement_id,work_unit_id,integration_id,settled_at)VALUES(?1,?2,?3,?4)",params![id("work-unit-settlement",iid),r.unit,iid,now]).map_err(|e|e.to_string())?;let edges=tx.prepare("SELECT relationship_id,from_id FROM work_unit_relationships WHERE relationship_kind='depends_on' AND to_id=?1 ORDER BY relationship_id").map_err(|e|e.to_string())?.query_map([&r.unit],|x|Ok((x.get::<_,String>(0)?,x.get::<_,String>(1)?))).map_err(|e|e.to_string())?.collect::<Result<Vec<_>,_>>().map_err(|e|e.to_string())?;for(edge,dependent)in edges{tx.execute("INSERT OR IGNORE INTO work_unit_prerequisite_contributions(contribution_id,prerequisite_work_unit_id,dependent_work_unit_id,integration_id,relationship_id,recorded_at)VALUES(?1,?2,?3,?4,?5,?6)",params![id("work-unit-prerequisite-contribution",&format!("{iid}:{edge}")),r.unit,dependent,iid,edge,now]).map_err(|e|e.to_string())?;}tx.execute("UPDATE accepted_work_unit_integrations SET settled_at=COALESCE(settled_at,?2),notification_intent_recorded_at=COALESCE(notification_intent_recorded_at,?2) WHERE integration_id=?1",params![iid,now]).map_err(|e|e.to_string())?;tx.commit().map_err(|e|e.to_string())?;Ok(())}
fn attention(c:&mut Connection,candidate:&str,code:&str)->Result<(),String>{c.execute("UPDATE accepted_work_unit_integrations SET attention_code=COALESCE(attention_code,?2),attention_recorded_at=COALESCE(attention_recorded_at,?3) WHERE candidate_id=?1",params![candidate,code,chrono::Utc::now().to_rfc3339()]).map_err(|e|e.to_string())?;Ok(())}
struct Lock{path:PathBuf}impl Lock{fn take(common:&Path,reference:&str)->Result<Self,String>{let path=common.join(format!("codex-orchestrator-{}.lock",id("target-ref-lock",reference)));OpenOptions::new().write(true).create_new(true).open(&path).map_err(|_|"target_lock_unavailable".to_string())?.sync_all().map_err(|_|"target_lock_unavailable".to_string())?;Ok(Self{path})}}impl Drop for Lock{fn drop(&mut self){let _=fs::remove_file(&self.path);}}
fn git(root:&Path,args:&[&str])->Result<String,String>{let o=Command::new("git").args(args).current_dir(root).stdin(Stdio::null()).output().map_err(|_|"git_unavailable".to_string())?;if o.status.success(){Ok(String::from_utf8_lossy(&o.stdout).trim().to_owned())}else{Err("git_command_failed".into())}}
fn git_index(root:&Path,args:&[&str],index:&Path)->Result<String,String>{let o=Command::new("git").args(args).env("GIT_INDEX_FILE",index).current_dir(root).stdin(Stdio::null()).output().map_err(|_|"git_unavailable".to_string())?;if o.status.success(){Ok(String::from_utf8_lossy(&o.stdout).trim().to_owned())}else{Err("git_command_failed".into())}}
fn canon(p:&Path)->Result<String,String>{p.canonicalize().map_err(|_|"path_unavailable".to_string()).map(|p|p.to_string_lossy().replace('\\',"/"))}fn safe_ref(v:&str)->bool{v.starts_with("refs/heads/")&&v.len()<256&&!v.contains("..")&&!v.contains(' ')&&!v.ends_with('/')}fn oid(v:&str)->bool{v.len()==40&&v.bytes().all(|x|x.is_ascii_hexdigit())}fn hash(v:&[&str])->String{let mut h=Sha256::new();for x in v{h.update(x.as_bytes());h.update([0]);}format!("{:x}",h.finalize())}fn id(d:&str,v:&str)->String{hash(&[d,v])[..32].to_owned()}

#[cfg(test)] mod tests { use super::*; use tempfile::TempDir;
 fn run(root:&Path,args:&[&str]){let status=Command::new("git").args(args).current_dir(root).status().unwrap();assert!(status.success(),"git {args:?}")}
 fn fixture()->(TempDir,Connection,Row){let dir=TempDir::new().unwrap();let root=dir.path();run(root,&["init","-b","main"]);run(root,&["config","user.name","Test User"]);run(root,&["config","user.email","test@example.invalid"]);fs::write(root.join("base.txt"),"base\n").unwrap();run(root,&["add","."]);run(root,&["commit","-m","base"]);let baseline=git(root,&["rev-parse","HEAD"]).unwrap();run(root,&["checkout","-b","candidate"]);fs::write(root.join("base.txt"),"candidate\n").unwrap();fs::write(root.join("candidate.txt"),"candidate\n").unwrap();run(root,&["add","."]);run(root,&["commit","-m","candidate"]);let candidate=git(root,&["rev-parse","HEAD"]).unwrap();let tree=git(root,&["rev-parse","HEAD^{tree}"]).unwrap();run(root,&["update-ref","refs/codex/orchestrator/accepted/candidate",&candidate]);run(root,&["checkout","main"]);let c=Connection::open_in_memory().unwrap();c.execute_batch("CREATE TABLE work_units(work_unit_id TEXT PRIMARY KEY);CREATE TABLE initiated_sprint_git_authorities(authority_id TEXT PRIMARY KEY,repository_root TEXT,repository_common_dir TEXT,worktree_root TEXT,baseline_object_id TEXT);CREATE TABLE accepted_handler_candidates(candidate_id TEXT PRIMARY KEY,work_unit_id TEXT,authority_id TEXT,pinned_at TEXT,attention_reason TEXT,candidate_commit_id TEXT,candidate_tree_id TEXT,private_ref_name TEXT,evidence_fingerprint TEXT);CREATE TABLE sprint_target_currents(authority_id TEXT PRIMARY KEY,target_ref_name TEXT,current_object_id TEXT,version INTEGER,attention_reason TEXT,updated_at TEXT);CREATE TABLE work_unit_relationships(relationship_id TEXT PRIMARY KEY,relationship_kind TEXT,from_id TEXT,to_id TEXT);").unwrap();c.execute("INSERT INTO work_units VALUES('unit')",[]).unwrap();let common=root.join(".git");c.execute("INSERT INTO initiated_sprint_git_authorities VALUES('authority',?1,?2,?1,?3)",params![root.to_string_lossy(),common.to_string_lossy(),baseline]).unwrap();let now=chrono::Utc::now().to_rfc3339();c.execute("INSERT INTO accepted_handler_candidates VALUES('candidate','unit','authority',?1,NULL,?2,?3,'refs/codex/orchestrator/accepted/candidate','evidence')",params![now,candidate,tree]).unwrap();c.execute("INSERT INTO sprint_target_currents VALUES('authority','refs/heads/main',?1,1,NULL,?2)",params![baseline,now]).unwrap();let row=Row{candidate:"candidate".into(),unit:"unit".into(),authority:"authority".into(),repo:root.to_path_buf(),common,worktree:root.to_path_buf(),baseline,commit:candidate,tree,private_ref:"refs/codex/orchestrator/accepted/candidate".into(),evidence:"evidence".into(),reference:"refs/heads/main".into(),current:git(root,&["rev-parse","HEAD"]).unwrap(),version:1};(dir,c,row)}
 #[test] fn baseline_parent_success_is_single_parent_and_exactly_once(){let(_d,mut c,row)=fixture();reconcile_accepted_integrations(&mut c).unwrap();let commit:String=c.query_row("SELECT integration_commit_id FROM accepted_work_unit_integrations",[],|r|r.get(0)).unwrap();assert_eq!(git(&row.repo,&["rev-parse",&format!("{commit}^{{tree}}")]).unwrap(),row.tree);assert_eq!(git(&row.repo,&["rev-list","--parents","-n","1",&commit]).unwrap(),format!("{commit} {}",row.current));reconcile_accepted_integrations(&mut c).unwrap();let attention:Option<String>=c.query_row("SELECT attention_code FROM accepted_work_unit_integrations",[],|r|r.get(0)).unwrap();assert_eq!(c.query_row::<i64,_,_>("SELECT COUNT(*) FROM work_unit_settlements",[],|r|r.get(0)).unwrap(),1,"attention={attention:?}");}
 #[test] fn conflict_records_attention_without_target_move(){let(_d,mut c,row)=fixture();fs::write(row.repo.join("base.txt"),"target\n").unwrap();run(&row.repo,&["add","."]);run(&row.repo,&["commit","-m","target advance"]);let before=git(&row.repo,&["rev-parse","HEAD"]).unwrap();c.execute("UPDATE sprint_target_currents SET current_object_id=?1",[&before]).unwrap();let mut advanced=row.clone();advanced.current=before.clone();reconcile_accepted_integrations(&mut c).unwrap();assert_eq!(git(&row.repo,&["rev-parse","HEAD"]).unwrap(),before);assert_eq!(c.query_row::<String,_,_>("SELECT attention_code FROM accepted_work_unit_integrations",[],|r|r.get(0)).unwrap(),"integration_conflict");let _=advanced;}
}
